import React, { useEffect, useState } from 'react';
import API from '../services/api';
import { BookOpen, CalendarClock, CircleHelp, FileText, Library, LogOut, RefreshCw, ShieldCheck, X } from 'lucide-react';

type Tab = 'overview' | 'library' | 'policies' | 'issues';

const StudentPortal: React.FC = () => {
  const [tab, setTab] = useState<Tab>('overview');
  const [data, setData] = useState<any>(null);
  const [issues, setIssues] = useState<any[]>([]);
  const [text, setText] = useState('');
  const [preview, setPreview] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState('');
  const user = (() => { try { return JSON.parse(localStorage.getItem('knust_lib_user') || '{}'); } catch { return {}; } })();

  const load = async () => {
    setLoading(true);
    try {
      const [a, b] = await Promise.all([API.get('/library/my-library'), API.get('/library/issues/my')]);
      setData(a.data.data); setIssues(b.data.data || []);
    } catch (e) { console.error(e); setNotice('Could not load some library information.'); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);

  const renew = async (uuid: string) => { try { const r = await API.post(`/library/loans/${uuid}/renew`); setNotice(r.data.message); await load(); } catch (e: any) { setNotice(e.response?.data?.error || 'Unable to renew this book.'); } };
  const cancel = async (id: number) => { try { await API.delete(`/library/reservations/${id}`); setNotice('Reservation cancelled.'); await load(); } catch (e: any) { setNotice(e.response?.data?.error || 'Unable to cancel reservation.'); } };
  const analyse = () => { const s = text.toLowerCase(); const category = /borrow|loan|due|return|renew|overdue/.test(s) ? 'BORROWING' : /reserv|hold|queue|pickup/.test(s) ? 'RESERVATION' : /login|password|account|email|student id|profile/.test(s) ? 'ACCOUNT' : /book|copy|barcode|shelf|catalog|catalogue/.test(s) ? 'CATALOGUE' : 'GENERAL'; const priority = /urgent|emergency|blocked|exam|deadline/.test(s) ? 'HIGH' : /not working|missing|wrong|incorrect|problem|issue/.test(s) ? 'NORMAL' : 'LOW'; setPreview({ category, priority }); };
  const submitIssue = async () => { if (text.trim().length < 10) return setNotice('Please describe the problem in at least 10 characters.'); try { const r = await API.post('/library/issues/intake', { description: text }); setPreview(r.data.data.extracted); setText(''); setNotice('Issue submitted successfully.'); await load(); } catch (e: any) { setNotice(e.response?.data?.error || 'Unable to submit the issue.'); } };
  const logout = () => { localStorage.removeItem('knust_lib_token'); localStorage.removeItem('knust_lib_user'); window.location.href = '/login'; };

  return <div className="min-h-screen bg-slate-50 text-slate-900">
    <header className="sticky top-0 z-20 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#7A1C2C] text-white"><Library className="h-5 w-5" /></div><div><b>KNUST Library</b><div className="text-xs text-slate-500">Student Library Portal</div></div></div><div className="flex items-center gap-4"><div className="hidden text-right sm:block"><b className="text-sm">{user.fullName || 'Student'}</b><div className="text-xs text-slate-500">{user.studentId || user.email || ''}</div></div><button onClick={logout} className="rounded-xl border p-2"><LogOut className="h-4 w-4" /></button></div></div></header>
    <div className="mx-auto grid max-w-7xl grid-cols-1 gap-6 px-5 py-6 lg:grid-cols-[240px_1fr]">
      <aside className="h-fit rounded-2xl border bg-white p-3 shadow-sm"><div className="px-3 py-2 text-[10px] font-black uppercase tracking-widest text-slate-400">My Library</div>{([['overview','Overview',BookOpen],['library','Borrowing & Reservations',Library],['policies','Library Policies',ShieldCheck],['issues','Report a Library Issue',CircleHelp]] as any[]).map(([id,label,Icon]) => <button key={id} onClick={() => setTab(id)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-bold ${tab === id ? 'bg-[#7A1C2C] text-white' : 'text-slate-600 hover:bg-slate-50'}`}><Icon className="h-4 w-4" />{label}</button>)}</aside>
      <main>{notice && <div className="mb-5 flex justify-between rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-800">{notice}<button onClick={() => setNotice('')}><X className="h-4 w-4" /></button></div>}{loading ? <div className="rounded-2xl border bg-white p-10 text-center text-slate-500"><RefreshCw className="mx-auto mb-3 h-6 w-6 animate-spin" />Loading your library...</div> : <>
        {tab === 'overview' && <><Title title={`Welcome back, ${user.fullName?.split(' ')[0] || 'Student'}.`} sub="Your borrowing, reservations, policies and library support in one place." /><div className="grid gap-4 sm:grid-cols-3"><Stat label="Borrowed" value={data?.borrowed?.length || 0} icon={BookOpen} /><Stat label="Reservations" value={data?.reservations?.filter((r:any) => r.status === 'PENDING').length || 0} icon={CalendarClock} /><Stat label="Outstanding Fines" value={`GH₵ ${Number((data?.fines || []).filter((f:any) => f.status !== 'PAID').reduce((n:number,f:any) => n + Number(f.amount || 0), 0)).toFixed(2)}`} icon={FileText} /></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel title="Current loans"><Loans items={(data?.borrowed || []).slice(0,3)} renew={renew} /></Panel><Panel title="Reservations"><Reservations items={(data?.reservations || []).slice(0,3)} cancel={cancel} /></Panel></div></>}
        {tab === 'library' && <><Title title="Borrowing & Reservations" sub="A reservation is a queue position, not a loan. You borrow the book after it becomes available to you." /><Panel title={`Borrowed books (${data?.borrowed?.length || 0})`}><Loans items={data?.borrowed || []} renew={renew} /></Panel><div className="h-5" /><Panel title={`Reservations (${data?.reservations?.length || 0})`}><Reservations items={data?.reservations || []} cancel={cancel} /></Panel><div className="mt-5 grid gap-4 md:grid-cols-3"><Step n="1" title="Find a book" text="Check the catalogue for availability." /><Step n="2" title="Borrow or reserve" text="Available copies are borrowed. Unavailable books can be reserved." /><Step n="3" title="Get access" text="When your reservation reaches you, you are notified and the copy can be checked out." /></div></>}
        {tab === 'policies' && <><Title title="Library Policies" sub="These rules are loaded from the library's current system settings." /><div className="grid gap-5 md:grid-cols-2"><Policy title="Borrowing" items={[`Maximum books: ${data?.policies?.maxBooksPerStudent}`,`Loan period: ${data?.policies?.loanDurationDays} days`,`Renewals allowed: ${data?.policies?.renewalLimit}`,`Grace period: ${data?.policies?.gracePeriodDays} days`]} /><Policy title="Fines" items={[`Daily rate: GH₵ ${data?.policies?.fineRatePerDay}`,`Maximum fine: GH₵ ${data?.policies?.maxFineAmount}`,'Fines are tied to your loan record','Contact library staff if you believe a fine is incorrect']} /></div></>}
        {tab === 'issues' && <><Title title="Report a Library Issue" sub="Describe the problem naturally and the system will suggest the category and priority." /><div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-2xl border bg-white p-6 shadow-sm"><b>What happened?</b><textarea value={text} onChange={e => setText(e.target.value)} rows={7} placeholder="Example: I borrowed a book last week but my account still shows the wrong due date..." className="mt-3 w-full rounded-2xl border bg-slate-50 p-4 text-sm outline-none focus:border-[#7A1C2C]" /><div className="mt-4 flex gap-3"><button onClick={analyse} disabled={text.trim().length < 10} className="rounded-xl border px-4 py-2 text-sm font-bold disabled:opacity-40">Analyse</button><button onClick={submitIssue} disabled={text.trim().length < 10} className="rounded-xl bg-[#7A1C2C] px-5 py-2 text-sm font-bold text-white disabled:opacity-40">Submit Issue</button></div></section><section className="rounded-2xl border bg-white p-6 shadow-sm"><b>Smart intake</b>{preview ? <div className="mt-4 space-y-4"><Badge label="Category" value={preview.category} /><Badge label="Priority" value={preview.priority} /></div> : <p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Suggestions appear here after you analyse the description.</p>}</section></div><div className="mt-5"><Panel title="My submitted issues">{issues.length ? issues.map(i => <div key={i.id} className="mb-3 rounded-xl border p-4"><div className="flex justify-between"><b>{i.title}</b><span className="text-xs font-bold">{i.status}</span></div><p className="mt-2 whitespace-pre-wrap text-xs text-slate-500">{i.description}</p></div>) : <p className="text-sm text-slate-500">No library issues reported yet.</p>}</Panel></div></>}
      </>}</main>
    </div>
  </div>;
};
const Title=({title,sub}:{title:string,sub:string})=><div className="mb-6"><h1 className="text-3xl font-black tracking-tight">{title}</h1><p className="mt-1 text-slate-500">{sub}</p></div>;
const Panel=({title,children}:{title:string,children:React.ReactNode})=><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="mb-4 font-black">{title}</h2>{children}</section>;
const Stat=({label,value,icon:Icon}:any)=><div className="rounded-2xl border bg-white p-5 shadow-sm"><Icon className="mb-4 h-5 w-5 text-[#7A1C2C]" /><div className="text-3xl font-black">{value}</div><div className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</div></div>;
const Loans=({items,renew}:any)=>!items.length?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No active borrowed books.</p>:<div className="space-y-3">{items.map((l:any)=><div key={l.loanUuid} className="flex flex-col justify-between gap-3 rounded-xl border p-4 sm:flex-row sm:items-center"><div><b>{l.book?.title || 'Book'}</b><div className="text-xs text-slate-500">Due {new Date(l.dueDate).toLocaleDateString()} · {l.daysRemaining >= 0 ? `${l.daysRemaining} days remaining` : `${Math.abs(l.daysRemaining)} days overdue`}</div></div><button onClick={()=>renew(l.loanUuid)} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold"><RefreshCw className="h-3.5 w-3.5" />Renew</button></div>)}</div>;
const Reservations=({items,cancel}:any)=>!items.length?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No reservations.</p>:<div className="space-y-3">{items.map((r:any)=><div key={r.id} className="flex flex-col justify-between gap-3 rounded-xl border p-4 sm:flex-row sm:items-center"><div><b>{r.book?.title || `Book #${r.targetId}`}</b><div className="text-xs text-slate-500">Status: {r.status}{r.queuePosition ? ` · Queue position ${r.queuePosition}` : ''}</div></div>{r.status==='PENDING'&&<button onClick={()=>cancel(r.id)} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-600">Cancel</button>}</div>)}</div>;
const Policy=({title,items}:any)=><div className="rounded-2xl border bg-white p-6 shadow-sm"><div className="mb-4 flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-[#7A1C2C]"/><h2 className="font-black">{title}</h2></div><ul className="space-y-3">{items.map((x:string)=><li key={x} className="border-b pb-3 text-sm text-slate-600 last:border-0">{x}</li>)}</ul></div>;
const Badge=({label,value}:any)=><div><div className="text-[10px] font-black uppercase tracking-widest text-slate-400">{label}</div><div className="mt-1 inline-flex rounded-full bg-[#7A1C2C]/5 px-3 py-1 text-sm font-black text-[#7A1C2C]">{value}</div></div>;
const Step=({n,title,text}:any)=><div className="rounded-xl bg-white border p-4"><div className="mb-3 flex h-7 w-7 items-center justify-center rounded-full bg-[#7A1C2C] text-xs font-black text-white">{n}</div><b>{title}</b><p className="mt-1 text-xs leading-relaxed text-slate-500">{text}</p></div>;
export default StudentPortal;
